Repository nicks96432/mltd-asset-downloader, pull requests merged in 2023-07, with the labels that each got.

#24 Replace unmaintained actions-rs/toolchain
  .github/workflows/build.yaml
  .github/workflows/check.yaml
Labels: type: enhancement, status: resolved, area: ci

#27 :bug: Fix statically linking on Windows
  acb/build.rs
Labels: type: bug, area: acb, status: resolved

#32 Setup CD tool for MacOS M1 build
  codemagic.yaml
Labels: type: feature, area: ci
